spring:
  datasource:
    url: >-
      jdbc:mysql://localhost/fornecedor?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 2416
  jpa:
    hibernate:
      ddl-auto: update
